### PR TITLE
rem: Do not show the default item

### PR DESCRIPTION
**Pull request by okb12**
Removed default "Open remmina" item since all connections are shown and it gets in the way by staying on top.

### CODE REVIEW

**Comment by bergercookie** [comment]
Maybe, instead of removing it altogether, insert it in the end of the items list?
I'm thinking of scenarios that one searches for a connection that may not have been created yet on the this machine.

In this case the user would instead want to launch remmina and create that connetion from scratch, thus it'd be useful to have it at least as the last item

What do you think?

**Comment by okb12** [comment]
Condition for showing "launch remmina" item should be results.length == 0 then. If I understood correctly that makes much more sense. I'll be working on it.

**Comment by bergercookie** [comment]
But what if you start typing, you do see results (so results.length != 0) but none of them match the name of the connection that you want? In that case I'd like to have the "Launch Remmina" option as last on the list, merely as a fallback.

**Comment by okb12** [comment]
I've tried changing urgency and id of the items but nothing worked. Ordering methods are not documented well. I should be studying the source code.

**Comment by bergercookie** [comment]
Hmm, probably you're on v0.3 of the albert python API

Try something like this:

```
def handleQuery(query) -> list:
    ....

    if query.isTriggered:
        try:
           ....
            # be backwards compatible with v0.2
            if "disableSort" in dir(query):
                query.disableSort()
```

Otherwise there must be a button in the albert settings for enabling/disabling the sorting

**Comment by bergercookie** [comment]
Hi @okb1100 , 

Is this PR still relevant?  Did my suggestion help?

**Comment by okb12** [comment]
Unfortunately your suggestion did not help. Default item still stays on top.

**Comment by bergercookie** [comment]
Hi @okb1100 , long time no see, I hope you're well :) 

I can repro your issue now that I've switched the latest v0.4.0 Albert API.
I've just pushed a commit to master and using that the default item now appears last on the last as expected.

Let me know if this works for you, closing this for now.

**Comment by okb12** [comment]
Hey! I'm glad to see you're still committed to the project, unfortunately I've swithed to the evil fruit OS but I'll test the changes if i get my hands on a linux workstation

**Pull request closed without merging**
